-- MySQL Script generated by MySQL Workbench
-- Sun Dec 20 21:46:11 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema kierklok
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kierklok
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kierklok` DEFAULT CHARACTER SET utf8 ;
USE `kierklok` ;

-- -----------------------------------------------------
-- Table `kierklok`.`projekt_ksiazki`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kierklok`.`projekt_ksiazki` (
  `id_ksiazki` INT NOT NULL AUTO_INCREMENT,
  `tytul` VARCHAR(255) NOT NULL,
  `imie_autora` VARCHAR(255) NULL,
  `nazwisko_autora` VARCHAR(255) NULL,
  `gatunek` VARCHAR(255) NULL,
  `rodzaj_okladki` VARCHAR(255) NULL,
  `cena` DECIMAL(5,2) NOT NULL,
  PRIMARY KEY (`id_ksiazki`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kierklok`.`projekt_pracownicy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kierklok`.`projekt_pracownicy` (
  `id_pracownika` INT NOT NULL AUTO_INCREMENT,
  `imie_pracownika` VARCHAR(255) NULL,
  `nazwisko_pracownika` VARCHAR(255) NULL,
  `adres_zamieszkania` VARCHAR(255) NULL,
  `data_zatrudnienia` DATE NULL,
  `pensja` DECIMAL(7,2) NOT NULL,
  `stanowisko` VARCHAR(255) NULL,
  PRIMARY KEY (`id_pracownika`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kierklok`.`projekt_zakupy_w_lokalu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kierklok`.`projekt_zakupy_w_lokalu` (
  `id_zakupu` INT NOT NULL AUTO_INCREMENT,
  `data_zakupu` DATE NULL,
  `ilosc_ksiazek_kupionych` INT NULL DEFAULT 1,
  `kwota_do_zaplaty` DECIMAL(5,2) NOT NULL,
  `projekt_ksiazki_id_ksiazki` INT NOT NULL,
  `projekt_pracownicy_id_pracownika` INT NOT NULL,
  PRIMARY KEY (`id_zakupu`, `projekt_ksiazki_id_ksiazki`, `projekt_pracownicy_id_pracownika`),
  INDEX `fk_projekt_zakupy_w_lokalu_projekt_ksiazki1_idx` (`projekt_ksiazki_id_ksiazki` ASC) VISIBLE,
  INDEX `fk_projekt_zakupy_w_lokalu_projekt_pracownicy1_idx` (`projekt_pracownicy_id_pracownika` ASC) VISIBLE,
  CONSTRAINT `fk_projekt_zakupy_w_lokalu_projekt_ksiazki1`
    FOREIGN KEY (`projekt_ksiazki_id_ksiazki`)
    REFERENCES `kierklok`.`projekt_ksiazki` (`id_ksiazki`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projekt_zakupy_w_lokalu_projekt_pracownicy1`
    FOREIGN KEY (`projekt_pracownicy_id_pracownika`)
    REFERENCES `kierklok`.`projekt_pracownicy` (`id_pracownika`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kierklok`.`projekt_klienci_online`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kierklok`.`projekt_klienci_online` (
  `id_klienta` INT NOT NULL AUTO_INCREMENT,
  `imie_klienta` VARCHAR(255) NULL,
  `nazwisko_klienta` VARCHAR(255) NULL,
  `adres_do_wysylki` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NULL,
  `numer_telefonu` VARCHAR(9) NULL,
  PRIMARY KEY (`id_klienta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kierklok`.`projekt_zamowienia_online`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kierklok`.`projekt_zamowienia_online` (
  `id_zamowienia` INT NOT NULL AUTO_INCREMENT,
  `data_zamowienia` DATE NULL,
  `ilosc_zamowionych_ksiazek` INT NULL DEFAULT 1,
  `wartosc_zamowienia` DECIMAL(6,2) NULL,
  `sposob_platnosci` VARCHAR(255) NULL,
  `status_zamowienia` VARCHAR(255) NULL,
  `projekt_ksiazki_id_ksiazki` INT NOT NULL,
  `projekt_klienci_online_id_klienta` INT NOT NULL,
  PRIMARY KEY (`id_zamowienia`, `projekt_ksiazki_id_ksiazki`, `projekt_klienci_online_id_klienta`),
  INDEX `fk_projekt_zamowienia_online_projekt_ksiazki1_idx` (`projekt_ksiazki_id_ksiazki` ASC) VISIBLE,
  INDEX `fk_projekt_zamowienia_online_projekt_klienci_online1_idx` (`projekt_klienci_online_id_klienta` ASC) VISIBLE,
  CONSTRAINT `fk_projekt_zamowienia_online_projekt_ksiazki1`
    FOREIGN KEY (`projekt_ksiazki_id_ksiazki`)
    REFERENCES `kierklok`.`projekt_ksiazki` (`id_ksiazki`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projekt_zamowienia_online_projekt_klienci_online1`
    FOREIGN KEY (`projekt_klienci_online_id_klienta`)
    REFERENCES `kierklok`.`projekt_klienci_online` (`id_klienta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kierklok`.`projekt_konto_klienta_online`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kierklok`.`projekt_konto_klienta_online` (
  `projekt_klienci_online_id_klienta` INT NOT NULL,
  `login` VARCHAR(255) NOT NULL,
  `haslo` VARCHAR(255) NOT NULL,
  `pytanie_pomocnicze` VARCHAR(255) NULL,
  `odpowiedz_na_pytanie` VARCHAR(255) NULL,
  `data_zalozenia_konta` DATE NULL,
  PRIMARY KEY (`projekt_klienci_online_id_klienta`),
  CONSTRAINT `fk_projekt_konto_klienta_online_projekt_klienci_online`
    FOREIGN KEY (`projekt_klienci_online_id_klienta`)
    REFERENCES `kierklok`.`projekt_klienci_online` (`id_klienta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
